### ISSUE TITLE
可以录制一个代码的测试演示视频吗？

### ISSUE THREAD

**Issue by Anton-yang-yang** [PING020903/AC695N-jieli--demo-GamePad#2]

**Comment by PING020903** [comment]
非常抱歉，这个硬件现在我手上并没有。不过我还是想问问，需要代码演示视频是要看这个实际效果如何吗


1256677528
***@***.***



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "PING020903/AC695N-demo-GamePad"                                                                                    ***@***.***&gt;;
Date:&nbsp;Fri, Dec 1, 2023 11:46 AM
***@***.***&gt;;
***@***.***&gt;;
Subject:&nbsp;[PING020903/AC695N-demo-GamePad] 可以录制一个代码的演示视频吗？ (Issue #2)

**Comment by PING020903** [comment]
https://item.taobao.com/item.htm?spm=a21n57.1.0.0.6132523cegBSF8&id=707572367685&ns=1&abbucket=20#detail

**Comment by Anton-yang-yang** [comment]
你好，563657748

**Comment by PING020903** [comment]
1256677528，这是我的QQ号&nbsp;


1256677528
***@***.***



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2023年12月5日(星期二) 上午10:12
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [PING020903/AC695N-demo-GamePad] 可以录制一个代码的测试演示视频吗？ (Issue #2)





 
你好，563657748
